[build]
publish = "_site"
command = "npm run build-production"

[[redirects]]
from = "/dynamic/"
to = "/.netlify/functions/serverless"
status = 200
force = true

[[redirects]]
from = "/:key/"
to = "/.netlify/functions/serverless"
status = 200
force = true

[[redirects]]
from = "/:key/cached/"
to = "/.netlify/functions/ondemandbuilder"
status = 200
force = true
